all done 2021 04 26
maksym-slinchenko/nodejs-homework-template pull request #1
Opened 2021-04-26 21:39 UTC by maksym-slinchenko

2021-04-28 07:27 UTC, SergeiKBB requested changes

2021-04-28 07:27 UTC, SergeiKBB commented on model/controllers.js
> +  const contacts = await listContacts();
у тебя listContacts синхроная функция. Почему ты решил здесь использовать await?

2021-04-28 07:27 UTC, SergeiKBB commented on model/controllers.js
> +  fs.writeFile(contactsPath, JSON.stringify(contacts, null, "\t"), (err) => {
Внутри асинхроной фукнции ты используешь колбеки. Плохая практика. Перепеши все на асинхроные функции.

2021-04-28 07:27 UTC, SergeiKBB commented on routes/api/contacts.js
> +    const body = await schemaAddContact.validateAsync(req.body);
почему ты не используешь мидылвару для валидации?

2021-04-30 19:13 UTC, maksym-slinchenko commented on model/controllers.js
> +  const contacts = await listContacts();
Не до конца еще понимаю необходимость применения асинхронных функций, поэтому и леплю их везде, где получается) Убрал await везде, где использую listContacts.

2021-04-30 19:13 UTC, maksym-slinchenko commented on model/controllers.js
> +  fs.writeFile(contactsPath, JSON.stringify(contacts, null, "\t"), (err) => {
Добавил await для fs.writeFile, если я правильно тебя понял. Но мне VS code пишет, что такая запись не имеет смысла. Или что в этом он понимает?)

2021-04-30 19:13 UTC, maksym-slinchenko commented on routes/api/contacts.js
> +    const body = await schemaAddContact.validateAsync(req.body);
Честно говоря мне непонятно зачем нам писать мидлвары, если можно без них валидировать запросы, применяя схему непосредственно в http-запросе через schema.validateAsync. Что дает дополнительное использование мидлвара, можешь объяснить? Я пока ничего не меня по этому пункту...

2021-04-30 19:38 UTC, SergeiKBB commented on routes/api/contacts.js
> +    const body = await schemaAddContact.validateAsync(req.body);
В двух словах: Single Responsibilities. Один из принципов SOLID. Твоя програма стает более масштабируемой при использовании мидлвар. Если у тебя 1 мидлвара используется в 10 роутах,  тебе достаточно будет изменить её логику в одном месте, в противном тебе пришлось бы бегать по всем 10 роутам.

2021-04-30 19:42 UTC, SergeiKBB requested changes

2021-04-30 19:42 UTC, SergeiKBB commented on model/controllers.js
> +    (err) => {
Нет смысла писать await когда ты используешь колбек. Почитай или посмотри видео по async await и перепеши используя только асинхроные функции (колбек нужно удалить) 
https://learn.javascript.ru/async-await
https://www.youtube.com/watch?v=SHiUyM_fFME&ab_channel=%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BB%D0%B5%D0%BD%D0%9C%D0%B8%D0%BD%D0%B8%D0%BD

2021-05-01 08:32 UTC, maksym-slinchenko commented on model/controllers.js
> +    (err) => {
Если речь о колбеке, где мы обрабатываем ошибку в fs.writeFile, то он там должен быть, так написано в доках по ноде: fs.writeFile(file, data[, options], callback)
Или о каком конкретном колбеке идет речь? Я уже вкрай запутался...

2021-05-01 08:33 UTC, maksym-slinchenko commented on routes/api/contacts.js
> +    const body = await schemaAddContact.validateAsync(req.body);
понятно. Добавил мидлвары

2021-05-01 12:29 UTC, SergeiKBB commented on model/controllers.js
> +    (err) => {
Об этом колбеке речь. В доке написано потому что они используют подход с колбеками. Если используешь асинк то ошибку обробатываешь в блоке catch

2021-05-03 08:51 UTC, SergeiKBB approved these changes

2021-05-04 10:52 UTC, maksym-slinchenko commented on model/controllers.js
> +    (err) => {
Привет. А что мне указывать в аргументах fs.writeFile() вместо callback? Это обязательный параметр. Или обработку ошибки нужно указать и в fs.writeFile() и в catch?

2021-05-04 17:52 UTC, SergeiKBB commented on model/controllers.js
> +    (err) => {
https://www.geeksforgeeks.org/node-js-fspromises-writefile-method/

2021-05-06 16:44 UTC, merged